namespace Academically.Domain.Enums
{
    public enum DocumentType
    {
        General,
        ProfilePicture,
        CoverPhoto,
        Qualification,
        Passport,
        Education,
        PhotoId,
        Reference,
        DbsCertificate,
        IntroVideo,
        Conversation,
        CourseImage,
        CourseSectionPage,
        CourseAssignment,
        Video,
        VideoThumbnail,
        ArticleThumbnail,
        CourseSectionImage,
        EventThumbnail,
        EventResource,
        Project,
        CoachingThumbnail,
        CoachingResource,
        WorkshopThumbnail,
        WorkshopResource,
        PostAttachment
    }
}
