stages:
  - build
  - deploy

variables:
#  PROJECT_NAME: "Admin.API"
  BUILD_IMAGE: "mcr.microsoft.com/dotnet/core/sdk:3.1" 
  ANGULAR_PATH: "code/Academically/Academically.Web.Host"
  ENV_NAME: "poc"
  LOG_RETENTION: 7
  ARTIFACT_RETENTION: 21
  SG_WEB: "sg-0e99d2ed26808a35d"
  PRIVATE_SUBNET_A: "subnet-03f6e008bbf99fd12"
  PRIVATE_SUBNET_B: "subnet-06ff7fbbb445833a3"
  PUBLIC_DOMAIN: "sourcecloud-dev.uk"

#########
# Build #
#########



build_backend:
  stage: build
  image: $BUILD_IMAGE
  before_script:
    - echo "pre script (build_backend)"
    - apt-get update
    - echo "Install Pre-requistes"
    - apt-get install -y zip
    - pwd
    - mkdir artifacts
    - "cd $CI_PROJECT_DIR/$ANGULAR_PATH" 
    - "dotnet restore"

  script:
    # Build and Package projects
    - "cd $CI_PROJECT_DIR/$ANGULAR_PATH" 
    - dotnet publish --configuration release --framework netcoreapp3.1 --output bin/release/netcoreapp3.1/output
    - zip -r $CI_PROJECT_DIR/artifacts/$CI_PROJECT_NAME.zip bin/release/netcoreapp3.1/output
    - ls -la
  artifacts:
    paths:
      - artifacts
    expire_in: 21 days

# End Build #
#############


###############
# Deployments #
###############

# Environment CI #



# End Deploy #
##############