stages:
  - build
  - development
  - testing

variables:
  BUILD_IMAGE: "mcr.microsoft.com/dotnet/core/sdk:3.1" 
  FRONTEND_PATH: "code/new/academically-admin"
  BACKEND_PATH: "code/new/Academically/src/Academically.Web.Host"

.schema: &schema
  stage: deploy
  image: ubuntu:18.04
  before_script:
    - printf '\e[95m%s pre script (deploy_schema) \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Install Pre-requistes \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Building %s for environment %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$APP_NAME" "$env_name"
    - printf '\e[95m%s Deploying to AWS Region - %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$AWS_DEFAULT_REGION"
    - apt-get update
    - apt-get install -y software-properties-common 
    - apt-get install -y iputils-ping
    - apt-get install -y zip
    # install python, awscli & jq
    - apt-get install -y python3-pip
    - pip3 install awscli boto boto3
    - apt-get install -y jq
    - aws --version
    - jq --version
    # install java 1.8
    - apt-get install -y openjdk-8-jre
    - java -version
    # install MySQL
    - apt-get install -y mysql-client
    - mysql -V
    # need 5.1.48 of mysql driver
    - aws s3 cp s3://wile-local-source/local/utils/mysql-connector-java-5.1.38.jar /usr/share/java/mysql-connector-java.jar
    - ls -la
     # Create SQL Script
    - |-
      SQLSCRIPT=$(cat <<-EOF
      CREATE DATABASE IF NOT EXISTS \`${APP_NAME}_${env_name}\` CHARACTER SET utf8 COLLATE utf8_general_ci;
      SHOW DATABASES;
      CREATE USER IF NOT EXISTS '${DB_APP_USER}'@'%' IDENTIFIED BY '${DB_APP_PASSWORD}';
      GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, SHOW VIEW ON \`${APP_NAME}_${env_name}\`.* TO '${DB_APP_USER}'@'%';
      EOF
      )
    - echo Debug - $SQLSCRIPT
    # download liquibase
    - aws s3 cp s3://wile-local-source/local/utils/liquibase-4.2.0.zip $CI_PROJECT_DIR/
    - unzip $CI_PROJECT_DIR/liquibase-4.2.0.zip -d /opt/liquibase
    - unzip $CI_PROJECT_DIR/artifacts/database.zip -d $CI_PROJECT_DIR/liquibase_scripts
    # install and config OpenVPN
    - which openvpn || (apt-get update -y -qq && apt-get install -y -qq openvpn) # Install openvpn if not available.
    - cat <<< $CLIENT_OVPN > /etc/openvpn/client.conf # Move vpn config from gitlab variable to config file.
    - cat <<< $CLIENT_OVPN_KEY > /etc/openvpn/client.key # Move vpn client.key from gitlab variable to file.
    - cat <<< $CLIENT_OVPN_CRT > /etc/openvpn/client.crt # Move vpn client.crt from gitlab variable to file.
    - cat <<< "cert /etc/openvpn/client.crt" >> /etc/openvpn/client.conf # Tell vpn config to use client.crt file.
    - cat <<< "key /etc/openvpn/client.key" >> /etc/openvpn/client.conf # Tell vpn config to use client.key file.
    - cat <<< "log /etc/openvpn/client.log" >> /etc/openvpn/client.conf # Tell vpn config to use log file.
    - which openvpn
    # Lookup Database Id
    - export DATABASE_ID=db-$APP_NAME-$env_name.$PUBLIC_DOMAIN
    - echo "Database Id $DATABASE_ID"
    # Connect to VPN
    - openvpn --config /etc/openvpn/client.conf --verb 5 --daemon # Start openvpn with config as a deamon.
    - sleep 30s # Wait for some time so the vpn can connect before doing anything else.
    - cat /etc/openvpn/client.log # Print the vpn log.

  script:
    - printf '\e[95m%s Update Database Schema \e[0m\n' "$(date +'%d-%m-%Y %T')"
    # Run Create Database and Application User
    - printf '\e[95m%s Creating Admin Database %s-%s AND User %s ON %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "${APP_NAME}" "${env_name}" "${DB_APP_USER}" "${DATABASE_ID}"
    - mysql -h $DATABASE_ID -u${db_admin_user} -p${db_master_password}  -e "$SQLSCRIPT"
    # run liquibase on RDS
    - "cd $CI_PROJECT_DIR/liquibase_scripts"
    - printf '\e[95m%s Run Liquibase on %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$DATABASE_ID"
    - printf '\e[95m%s Clear Checksums \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - /opt/liquibase/liquibase --url="jdbc:mysql://$DATABASE_ID:3306/$APP_NAME``_$env_name?useSSL=false" --username=${db_admin_user} --password=${db_master_password} --changeLogFile=main.changelog.xml --classpath=/usr/share/java/mysql-connector-java.jar --driver=com.mysql.jdbc.Driver clearchecksums
    - printf '\e[95m%s Run Liquibase Scripts \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - /opt/liquibase/liquibase --url="jdbc:mysql://$DATABASE_ID:3306/$APP_NAME``_$env_name?useSSL=false" --username=${db_admin_user} --password=${db_master_password} --changeLogFile=main.changelog.xml --classpath=/usr/share/java/mysql-connector-java.jar --driver=com.mysql.jdbc.Driver update
    - printf '\e[95m%s Update Schema complete \e[0m\n' "$(date +'%d-%m-%Y %T')"


.backend: &backend
  stage: deploy
  image: node:latest
  before_script:
    - printf '\e[95m%s pre script (deploy_backend) \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Install Pre-requistes \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Building %s for environment %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$APP_NAME" "$env_name"
    - printf '\e[95m%s Deploying to AWS Region - %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$AWS_DEFAULT_REGION"
    - apt-get update
    # install python, awscli & jq
    - apt-get install -y python3-pip
    - pip3 install awscli boto boto3
    - apt-get install -y jq
    - aws --version
    - jq --version
    - apt-get install -y zip
    # install node and serverless
    - npm init -y
    - npm install
    # - npm install -g serverless
    # Lookup Required Outputs from AWS SSM
    - export ASG=$(aws ssm get-parameter --name "/$APP_NAME/$env_name/asg" | jq -r --raw-output '.Parameter.Value')
    - printf '\e[95m%s API ASG Name - %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$ASG"
    # Lookup Required Outputs from AWS SSM
    - export SG_WEB=$(aws ssm get-parameter --name "/$APP_NAME/$env_name/web_sg_id" | jq -r --raw-output '.Parameter.Value')
    - printf '\e[95m%s SG Web is - %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$SG_WEB"
    # Lookup Database Id
    - export DATABASE_ID=db-$APP_NAME-$env_name.$PUBLIC_DOMAIN
    - printf '\e[95m%s DatabaseId is - %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$DATABASE_ID"
    - pwd
    
  script:
    # Deploy using serverless
    - "cd $CI_PROJECT_DIR" 
    - "pwd"
    - "ls -la"
    - echo "Create package.json"
    - yarn install
    - yarn init --yes 2>/dev/null
    # - echo "install plugins"
    # - "yarn add serverless-plugin-log-retention --dev"
    # - "yarn add serverless-domain-manager@6.4.4 --dev"    # Hard code due to issue with 7.0.0
    # perform subsitutions on appsettings (need to unzip and rezip)
    - mkdir $CI_PROJECT_DIR/temp
    - unzip $CI_PROJECT_DIR/artifacts/backend.zip -d $CI_PROJECT_DIR/temp
    - rm $CI_PROJECT_DIR/artifacts/backend.zip # remove zip so we can create a new one
    - cd temp
    - >
      if [[ "$env_name" == "ci" ]]; then
        export API_URL="https://api-$APP_NAME-$env_name.$PUBLIC_DOMAIN"
        export URL_HTTPS="https://$APP_NAME-$env_name.$PUBLIC_DOMAIN"
        export URL_HTTP="http://$APP_NAME-$env_name.$PUBLIC_DOMAIN"
      else 
        export API_URL="https://api-$env_name.$PUBLIC_DOMAIN"
        export URL_HTTPS="https://$env_name.$PUBLIC_DOMAIN"
        export URL_HTTP="http://$env_name.$PUBLIC_DOMAIN"
      fi

    - echo $API_URL
    - cp appsettings.json appsettings.bak
    - cp log4net.config log4net.bak
    # Configure Logging jq, no good file is XML not json
    - sed -i 's|App_Data/Logs/Logs.txt|/var/log/'"$APP_NAME"'/'"$APP_NAME"'.log|g' log4net.config # Add gitlab to APP_NAME whilst in transition between projects

    # Configure AppSettings
    # Subsitute the Connection String
    - jq ".ConnectionStrings.Default=\"server=$DATABASE_ID``;database=$APP_NAME``_$env_name;uid=${db_admin_user};password=$db_master_password;port=3306\"" appsettings.bak > appsettings.v1
    # Subsitute the Other Variables
    - jq ".App.ClientRootAddress=\"$URL_HTTPS\" | .App.CorsOrigins=\"$URL_HTTPS``,$URL_HTTP\" | .App.ServerBasePath=\"\" | .Kestrel.Endpoints.Http.Url=\"http://localhost:5000\" | .Aws.Id=\"$AWS_ACC_NUM\" | .Aws.Profile=\"\" | .Aws.Region=\"$AWS_DEFAULT_REGION\" | .Aws.S3.AssetsBucket=\"$APP_NAME``-$env_name``-assets\" | .Aws.S3.SecureAssetsBucket=\"$APP_NAME``-$env_name``-assets-secure\" | .ITagg.Sms.Username=\"d9d7ec2c\" | .ITagg.Sms.Password=\"p5sswm6g\"" appsettings.v1 > appsettings.json
   
    - cat appsettings.json
    - rm appsettings.bak
    - zip -r $CI_PROJECT_DIR/artifacts/backend.zip .

    # Copy iis artifacts to S3 for deployment
    - cd $CI_PROJECT_DIR/artifacts/
    - ls -la # debug line
    - aws s3 rm s3://$APP_NAME-$env_name-artifacts/ --recursive
    - aws s3 cp . s3://$APP_NAME-$env_name-artifacts/ --recursive
    - aws s3 ls s3://$APP_NAME-$env_name-artifacts
    # Now Refresh the code on the EC2 Server
    - printf '\e[95m%s Reset InstanceRefresh Tag on ASG %s to force refresh on %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$ASG" "$env_name"
    - > 
      aws autoscaling create-or-update-tags
      --tags ResourceId=$ASG,ResourceType=auto-scaling-group,Key=InstanceRefresh,Value=$CI_JOB_STARTED_AT,PropagateAtLaunch=true
    - >
      aws autoscaling start-instance-refresh 
      --auto-scaling-group-name $ASG 
      --preferences '{"InstanceWarmup": 240, "MinHealthyPercentage": 50}'
    - printf '\e[95m%s Update Backend complete \e[0m\n' "$(date +'%d-%m-%Y %T')"


.frontend: &frontend
  stage: deploy
  image: node:latest
  before_script:
    - printf '\e[95m%s pre script (deploy_frontend) \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Install Pre-requistes \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Building %s for environment %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$APP_NAME" "$env_name"
    - printf '\e[95m%s Deploying to AWS Region - %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$AWS_DEFAULT_REGION"
    - printf '\e[95m%s Deploying to Domain - %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$PUBLIC_DOMAIN"
    - apt-get update
    - node -v
    - npm -v
    # install python, awscli & jq
    - apt-get install -y python3-pip
    - pip3 install awscli boto boto3
    - apt-get install -y jq
    - aws --version
    - jq --version
    - apt-get install -y zip
    # Run the following command ref: AUT-1123
    - export NODE_OPTIONS=--openssl-legacy-provider
    # Install Angular, specify v9.1.4 to match our code
    - npm install -g @angular/cli@9.1.4
    - pwd
  
  script:
    # build dist previously saved as an artifact
    - echo "Build $env_name"
    - "cd $CI_PROJECT_DIR/artifacts" 
    - ls -la
    - ng build --configuration $env_name
    # Copy Dist to S3 Bucket
    - echo "Copy dist to S3"
    - >
      if [[ "$env_name" == "ci" ]]; then
        aws s3 rm s3://$APP_NAME-$env_name.$PUBLIC_DOMAIN --recursive
        aws s3 cp dist s3://$APP_NAME-$env_name.$PUBLIC_DOMAIN --recursive
        aws s3 ls s3://$APP_NAME-$env_name.$PUBLIC_DOMAIN
      else 
        aws s3 rm s3://$env_name.$PUBLIC_DOMAIN --recursive
        aws s3 cp dist s3://$env_name.$PUBLIC_DOMAIN --recursive
        aws s3 ls s3://$env_name.$PUBLIC_DOMAIN
      fi
    - printf '\e[95m%s Update Frontend complete \e[0m\n' "$(date +'%d-%m-%Y %T')"


#########
# Build #
#########

build_schema:
  stage: build
  image: $BUILD_IMAGE
  before_script:
    - printf '\e[95m%s pre script (build_schema) \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Install Pre-requistes \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Building %s for environment %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$APP_NAME" "$env_name"
    - printf '\e[95m%s Deploying to AWS Region - %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$AWS_DEFAULT_REGION"
    - apt-get update
    - echo "Install Pre-requistes"
    - apt-get install -y zip
    - pwd
    - mkdir artifacts
  script:
    # Package Schema
    - "cd $CI_PROJECT_DIR/database" 
    - zip -r $CI_PROJECT_DIR/artifacts/database.zip .
    - echo "Zipped Packages Ready....."
    - "cd $CI_PROJECT_DIR/artifacts" 
    - ls -la
  artifacts:
    paths:
      - artifacts
    expire_in: 21 day
  only:
    - develop

build_backend:
  stage: build
  image: $BUILD_IMAGE
  before_script:
    - printf '\e[95m%s pre script (build_backend) \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Install Pre-requistes \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Building %s for environment %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$APP_NAME" "$env_name"
    - printf '\e[95m%s Deploying to AWS Region - %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$AWS_DEFAULT_REGION"
    - apt-get update
    - echo "Install Pre-requistes"
    - apt-get install -y zip
    - pwd
    - mkdir artifacts
    - "cd $CI_PROJECT_DIR/$BACKEND_PATH" 
    - "dotnet restore"

  script:
    # Build and Package projects
    - "cd $CI_PROJECT_DIR/$BACKEND_PATH" 
    - dotnet publish --configuration release --framework netcoreapp3.1 --output bin/release/netcoreapp3.1/output
    - "cd $CI_PROJECT_DIR/$BACKEND_PATH/bin/release/netcoreapp3.1/output" 
    - zip -r $CI_PROJECT_DIR/artifacts/backend.zip .
    - ls -la
  artifacts:
    paths:
      - artifacts
    expire_in: 21 days # does not support parameter: https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/1893
  only:
    - develop

build_frontend:
  stage: build
  image: node:latest
  before_script:
    - printf '\e[95m%s pre script (build_frontend) \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Install Pre-requistes \e[0m\n' "$(date +'%d-%m-%Y %T')"
    - printf '\e[95m%s Building %s for environment %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$APP_NAME" "$env_name"
    - printf '\e[95m%s Deploying to AWS Region - %s \e[0m\n' "$(date +'%d-%m-%Y %T')" "$AWS_DEFAULT_REGION"
    - apt-get update
    - node -v
    - npm -v
  cache:
    paths:
      - $CI_PROJECT_DIR/$FRONTEND_PATH/node_modules/
      
  script:
    - "cd $CI_PROJECT_DIR/$FRONTEND_PATH"
    # specify v9.1.4 to match our code
    - npm install -g @angular/cli@9.1.4
    - yarn install    
    - ls -la
    - cp -r $CI_PROJECT_DIR/$FRONTEND_PATH/ $CI_PROJECT_DIR/artifacts/
  artifacts:
    paths:
      - artifacts
    expire_in: 21 day
  only:
    - develop

    
# End Build #
#############


###############
# Deployments #
###############

# Environment CI #

deploy_schema_to_ci:
  <<: *schema
  stage: development
  dependencies:
    - build_schema
  needs:
    - build_schema
  variables:
    env_name: ci
  environment:
    name: ci
    deployment_tier: development
  only:
    - develop

# deploy_backend_to_ci:
#   <<: *backend
#   stage: development
#   dependencies:
#     - build_backend
#   needs:
#     - build_backend
#   variables:
#     env_name: ci
#   environment:
#     name: ci
#     deployment_tier: development
#   only:
#     - develop

# deploy_frontend_to_ci:
#   <<: *frontend
#   stage: development
#   dependencies:
#     - build_frontend
#   needs:
#     - build_frontend
#   variables:
#     env_name: ci
#   environment:
#     name: ci
#     deployment_tier: development
#   only:
#     - develop


deploy_schema_to_uat:
  <<: *schema
  stage: testing
  dependencies:
    - build_schema
  needs:
    - build_schema
  variables:
    env_name: uat
  environment:
    name: uat
    deployment_tier: testing
  only:
    - develop
  when: manual

# deploy_backend_to_uat:
#   <<: *backend
#   stage: testing
#   needs:    
#     - build_backend
#   dependencies:
#     - build_backend
#   variables:
#     env_name: uat
#   environment:
#     name: uat
#     deployment_tier: testing
#   when: manual
#   only:
#     - develop


# deploy_frontend_to_uat:
#   <<: *frontend
#   stage: testing
#   variables:
#     env_name: uat
#   dependencies:
#     - build_frontend
#   environment:
#     name: uat
#     deployment_tier: testing
#   when: manual
#   only:
#     - develop


# Environment UAT #

# End Deploy #
##############