stages:
  - build
  - deploy

variables:
  BUILD_IMAGE: "mcr.microsoft.com/dotnet/core/sdk:3.1" 
  FRONTEND_PATH: "code/academically-admin"
  BACKEND_PATH: "code/Academically/Academically.Web.Host"
  ENV_NAME: "ci"
  LOG_RETENTION: 7
  SG_WEB: "sg-0e99d2ed26808a35d"
  PRIVATE_SUBNET_A: "subnet-03f6e008bbf99fd12"
  PRIVATE_SUBNET_B: "subnet-06ff7fbbb445833a3"
  PUBLIC_DOMAIN: "sourcecloud-dev.uk"


#########
# Build #
#########

# build_schema:
#   stage: build
#   image: $BUILD_IMAGE
#   before_script:
#     - echo "pre script (build_schema)"
#     - apt-get update
#     - echo "Install Pre-requistes"
#     - apt-get install -y zip
#     - pwd
#     - mkdir artifacts

#   script:
#     # Package Schema
#     - "cd $CI_PROJECT_DIR/database" 
#     - zip -r $CI_PROJECT_DIR/artifacts/database.zip .
#     - echo "Zipped Packages Ready....."
#     - "cd $CI_PROJECT_DIR/artifacts" 
#     - ls -la
#   artifacts:
#     paths:
#       - artifacts
#     expire_in: 21 day

build_backend:
  stage: build
  image: $BUILD_IMAGE
  before_script:
    - echo "pre script (build_backend)"
    - apt-get update
    - echo "Install Pre-requistes"
    - apt-get install -y zip
    - pwd
    - mkdir artifacts
    - "cd $CI_PROJECT_DIR/$BACKEND_PATH" 
    - "dotnet restore"

  script:
    # Build and Package projects
    - "cd $CI_PROJECT_DIR/$BACKEND_PATH" 
    - dotnet publish --configuration release --framework netcoreapp3.1 --output bin/release/netcoreapp3.1/output
    - zip -r $CI_PROJECT_DIR/artifacts/backend.zip bin/release/netcoreapp3.1/output
    - ls -la
  artifacts:
    paths:
      - artifacts
    expire_in: 21 days # does not support parameter: https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/1893


# build_frontend:
#   stage: build
#   image: node:10.16.0
#   before_script:
#     - echo "pre script (build_frontend)"
#     - echo "Install Pre-requistes"
#     - apt-get update
#     - node -v
#     - npm -v
#   cache:
#     paths:
#       - $CI_PROJECT_DIR/$FRONTEND_PATH/node_modules/
      
#   script:
#     - "cd $CI_PROJECT_DIR/$FRONTEND_PATH"
#     - ls -la
#     # specify v9.1.4 to match our code
#     - npm install -g @angular/cli@9.1.4
#     - yarn install
#     - ng build --configuration $ENV_NAME
#     - ls -la
#   artifacts:
#     paths:
#       - $CI_PROJECT_DIR/$FRONTEND_PATH/dist/
#     expire_in: 21 day
    
# End Build #
#############


###############
# Deployments #
###############

# Environment CI #

deploy_backend:
  stage: deploy
  image: node:latest
  before_script:
    - echo "pre script (deploy_backend)"
    - echo "Install Pre-requistes"
    - echo "Deploy to AWS Region - $AWS_DEFAULT_REGION"
    - apt-get update
    - apt-get install -y zip
    - npm install
    - npm install -g serverless
    - pwd
  dependencies:
    - build_backend
  environment:
    name: ci_backend

  script:
    # Deploy using serverless
    - "cd $CI_PROJECT_DIR" 
    - "pwd"
    - "ls -la"
    - echo "Create package.json"
    - yarn install
    - yarn init --yes 2>/dev/null
    - echo "install plugins"
    - "yarn add serverless-plugin-log-retention --dev"
    - "yarn add serverless-domain-manager --dev"
    - echo "run serverless-domain-manager"
    - "SLS_DEBUG=* serverless create_domain"
    - echo "run serverless deploy"
    - "SLS_DEBUG=* serverless deploy"  


# End Deploy #
##############