---
# Transpositions for Lambda API package
# Step 1: Lookup RDS DB Name
# Step 2: Subsitute settings (serverless.yml) 
# Step 3: Re Archive Package

- name: Looking up Stack Details
  set_fact:
    stack_name: "{{app_name}}{{env_name}}"

- name: register cloudformation facts (run locally)
  cloudformation_facts:
    region: "{{aws_region}}"
    stack_name: "{{stack_name}}"
  delegate_to: localhost
  register: my_stack


  # Update appsettings settings for Lambda Function (Lambda packaged post website deploy)
- name: Update appsettings settings for Public Lambda Function
  template:
    src: templates/appsettings.json.j2
    dest: ../../casemix_pub_api/bin/release/netcoreapp3.1/casemix-pub-api/appsettings.json
  delegate_to: localhost


- name: Archive Lambda Distribution ready for deployment
  archive:
    path: ../../casemix_pub_api/bin/release/netcoreapp3.1/casemix-pub-api/*
    dest: ../../casemix_pub_api/bin/release/netcoreapp3.1/casemix-pub-api.zip
    format: zip
  delegate_to: localhost
  become: yes

- name: DEBUG where is serverless
  shell: |
    echo DEBUG - where is serverless.yml
    pwd
    sudo tree ../../casemix_pub_api/bin/release/netcoreapp3.1/casemix-pub-api
  delegate_to: localhost

  # Update serverless settings for Lambda Function (Lambda packaged post website deploy)
- name: Update serverless settings for Public Lambda Function
  template:
    src: templates/serverless.yml.j2
    dest: ../../casemix_pub_api/serverless.yml
  delegate_to: localhost