---
# The purpose of this playbook is to paramitise the Lambda distribution package to the correct environment
- name: STAGE1 - Prepare Lambda Distribution for correct environment
  hosts: localhost
  remote_user: deploy
  gather_facts: false
  vars_files:
    - ../group_vars/all.yml # global variables
    - ../group_vars/{{env_name}}-config.yml # global variables
#    - group_vars/{{env_name}}-config.yml

  roles:
    - common # lets go.....



