---
# file: roles/infrastructure/tasks/main.xml

- name: Provision CaseMix infrastructure using CloudFormation
  cloudformation:
    stack_name: "{{app_name}}{{env_name}}"
    state: "present"
    region: "{{aws_region}}"
    disable_rollback: true
    template: "cloudformation/deployer.yml"
    template_parameters:
      EnvName: "{{env_name}}"
      CostCode: "{{cost_code}}"
      NameSpace: "{{env_name}}-{{app_name}}.aws"
      VPC: "{{vpc}}"
      HostedZoneName: "{{public_domain}}"
      AvailabilityZone: "{{prefered_availability_zone}}"
      WebServerPort: "{{web_server_port}}"
      AnsibleWorkerCIDR: "{{ansible_worker_cidr}}"
      SCVpnCIDR: "{{sc_vpn_cidr}}"
      BaseSubnetA: "{{private_subnet_a}}"
      InternalSubnets: "{{private_subnets}}"
      DatabaseSubnets: "{{local_subnets}}"
      AnsibleInventoryId: "{{app_name}}{{env_name}}"
      ACMARN: "{{acm_arn}}"
      BackupRetention: "{{backup_retention}}"
      DBPort: "{{database_port}}"
      DBInstanceClass: "{{db_instance_class}}"
      DBEngine: "{{db_engine}}"
      DBEngineShort: "{{db_engine_short}}"
      DBEngineVersion: "{{db_engine_version}}"
      DBParameterGroupFamilyVer: "{{db_parameter_family_version}}"
      DBStorage: "{{db_storage}}"
      DBSnapshot: "{{snapshot_name}}"
      DBRestore: "{{restore}}"
      DBUser: "{{db_user}}"
      DBMasterUserPassword: "{{db_master_user_password}}"
      DBMultiAZ: "{{multi_az}}"
      DBEncrypt: "{{database_encryption}}"
      DefaultTTL: "{{default_ttl}}"
      MaxTTL: "{{max_ttl}}"
      MinTTL: "{{min_ttl}}"

# Look up stack details so we can use CloudFormation Export values
- name: Looking up Stack Details
  set_fact:
    stack_name: "{{app_name}}{{env_name}}"
  tags:
    - facts 
 