---
# file: group_vars/ci-config.xml

############################################
# GLOBAL VARS - avaialble to all playbooks #
############################################

# Project Cost Code
cost_code: academically


# SQL user
db_user: deployAdmin
db_app_user: dbUser  # This name is reference in liquibase scripts so must remain
db_name: academically_uat
database_port: 3306

aws_region: eu-west-2                   # London

# Public Domain
# This is not the FQDN, just the main domain, sub domain will be prepended with stack name
# NOW PASSED FROM OCTOPUS AS A VARIABLE
# public_domain: sourcecloud-dev.co.uk

web_server_port: 80

#####################
# Academically Config
#####################


# Cloudfront Cache Settings
default_ttl: 30
max_ttl: 30
min_ttl: 10

acm_arn: arn:aws:acm:us-east-1:761676740162:certificate/b5733d6c-6981-48f1-a97a-e082d2099bea # ARN of SSL *.sourcecloud-dev.co.uk NOTE must be in North Virginia for Cloudfront
