export const fileUploadConfiguration = {
  allowedImageExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
  ],
  allowedFileExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
    '.ppt',
    '.pptx',
    '.odt',
    '.xls',
    '.xlsx',
    '.ods',
    '.txt',
  ],
  allowedQualificationExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
  ],
  allowedReferenceExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
  ],
  allowedDbsCertificateExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
  ],
  videoExtensions: [
    '.mp4',
    '.mov',
    '.wmv',
    '.avi',
    '.mkv',
  ],
  powerPointExtensions: [
    '.ppt',
    '.pptx',
  ],
  maxFileSize: 5242880,
  folders: {
    video: 'videos',
    videoThumbnail: 'video-thumbnails',
    articleThumbnail: 'article-thumbnails',
    courseSectionImage: 'course-section-images',
    eventThumbnail: 'event-thumbnails',
    profilePicture: 'profile-pictures',
    eventResource: 'event-resources',
  },
};
