export const fileUploadConfiguration = {
  allowedImageExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
  ],
  allowedFileExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
    '.ppt',
    '.pptx',
    '.odt',
    '.xls',
    '.xlsx',
    '.ods',
    '.txt',
  ],
  allowedQualificationExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
  ],
  allowedReferenceExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
  ],
  allowedDbsCertificateExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
  ],
  videoExtensions: [
    '.mp4',
    '.mov',
    '.wmv',
    '.avi',
    '.mkv',
  ],
  powerPointExtensions: [
    '.ppt',
    '.pptx',
  ],
  msOfficeExtensions: [
    '.doc',
    '.dot',
    '.docx',
    '.dotx',
    '.docx',
    '.dotx',
    '.docm',
    '.dotm',
    '.xls',
    '.xlt',
    '.xla',
    '.xlsx',
    '.xltx',
    '.xlsm',
    '.xltm',
    '.xlam',
    '.xlsb',
    '.ppt',
    '.pot',
    '.pps',
    '.ppa',
    '.pptx',
    '.potx',
    '.ppsx',
    '.ppam',
    '.pptm',
    '.potm',
    '.ppsm',
  ],
  audioExtensions: [
    '.mp3',
    '.wav',
    '.ogg',
  ],
  maxFileSize: 5242880,
  folders: {
    video: 'videos',
    videoThumbnail: 'video-thumbnails',
    articleThumbnail: 'article-thumbnails',
    courseSectionImage: 'course-section-images',
    coachingThumbnail: 'coaching-thumbnails',
    eventThumbnail: 'event-thumbnails',
    profilePicture: 'profile-pictures',
    eventResource: 'event-resources',
  },
};
