export const fileUploadConfiguration = {
  allowedImageExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
  ],
  allowedFileExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
  ],
  allowedQualificationExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
  ],
  allowedReferenceExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
  ],
  allowedDbsCertificateExtensions: [
    '.jpg',
    '.jpeg',
    '.png',
    '.pdf',
    '.doc',
    '.docx',
  ],
  videoExtensions: [
    '.mp4',
    '.mov',
    '.wmv',
    '.avi',
    '.mkv',
  ],
  maxFileSize: 5242880,
};
